// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/aluno/delete-file': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/aluno/delete-file.post').default>>>>
    }
    '/api/aluno/documentos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/aluno/documentos.get').default>>>>
    }
    '/api/aluno/processos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/aluno/processos.get').default>>>>
    }
    '/api/aluno/save-answer': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/aluno/save-answer.post').default>>>>
    }
    '/api/aluno/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/aluno/upload.post').default>>>>
    }
    '/api/common/documentos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/common/documentos.get').default>>>>
    }
    '/api/cursos/disponiveis': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cursos/disponiveis.get').default>>>>
    }
    '/api/educacional/calendario': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/educacional/calendario.get').default>>>>
    }
    '/api/educacional/calendario/evento': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/educacional/calendario/evento.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/educacional/calendario/evento.post').default>>>>
    }
    '/api/educacional/calendario/upsert': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/educacional/calendario/upsert.post').default>>>>
    }
    '/api/educacional/curso': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/educacional/curso.post').default>>>>
    }
    '/api/educacional/curso/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/educacional/curso/[id].get').default>>>>
    }
    '/api/educacional/cursos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/educacional/cursos.get').default>>>>
    }
    '/api/educacional/diario': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/educacional/diario.get').default>>>>
    }
    '/api/educacional/diario/verificar': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/educacional/diario/verificar.get').default>>>>
    }
    '/api/educacional/turma': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/educacional/turma.post').default>>>>
    }
    '/api/educacional/turmas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/educacional/turmas.get').default>>>>
    }
    '/api/inscricao/delete-file': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inscricao/delete-file.post').default>>>>
    }
    '/api/inscricao/form': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inscricao/form.get').default>>>>
    }
    '/api/inscricao/save': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inscricao/save.post').default>>>>
    }
    '/api/inscricao/submit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inscricao/submit.post').default>>>>
    }
    '/api/inscricao/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inscricao/upload.post').default>>>>
    }
    '/api/matriculas/alunos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/matriculas/alunos.get').default>>>>
    }
    '/api/matriculas/faltas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/matriculas/faltas.get').default>>>>
    }
    '/api/matriculas/rematricula': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/matriculas/rematricula.post').default>>>>
    }
    '/api/matriculas/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/matriculas/stats.get').default>>>>
    }
    '/api/matriculas/status': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/matriculas/status.post').default>>>>
    }
    '/api/matriculas/turmas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/matriculas/turmas.get').default>>>>
    }
    '/api/me': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/me').default>>>>
    }
    '/api/producao/calendario/horarios': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/calendario/horarios.get').default>>>>
    }
    '/api/producao/calendario/reservas': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/calendario/reservas.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/calendario/reservas.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/calendario/reservas.post').default>>>>
    }
    '/api/producao/dashboard/activity': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/dashboard/activity.get').default>>>>
    }
    '/api/producao/dashboard/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/dashboard/stats.get').default>>>>
    }
    '/api/producao/dashboard/weekly': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/dashboard/weekly.get').default>>>>
    }
    '/api/producao/estoque/adicionar-lote': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/adicionar-lote.post').default>>>>
    }
    '/api/producao/estoque/associate': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/associate.put').default>>>>
    }
    '/api/producao/estoque/avaria': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/avaria.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/avaria.put').default>>>>
    }
    '/api/producao/estoque/categorias': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/categorias.get').default>>>>
    }
    '/api/producao/estoque/item': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/item.delete').default>>>>
    }
    '/api/producao/estoque/itens': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/itens.get').default>>>>
    }
    '/api/producao/estoque/produto': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/produto.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/produto.post').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/produto.put').default>>>>
    }
    '/api/producao/estoque/produtos-disponiveis': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/produtos-disponiveis.get').default>>>>
    }
    '/api/producao/estoque/produtos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/produtos.get').default>>>>
    }
    '/api/producao/estoque/reserva-itens': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/reserva-itens.post').default>>>>
    }
    '/api/producao/estoque/reserva-status': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/reserva-status.put').default>>>>
    }
    '/api/producao/estoque/reserva': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/reserva.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/reserva.post').default>>>>
    }
    '/api/producao/estoque/reservas': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/reservas.get').default>>>>
    }
    '/api/producao/estoque/tipos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/tipos.get').default>>>>
    }
    '/api/producao/estoque/unidades': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/unidades.get').default>>>>
    }
    '/api/producao/estoque/users-reserva': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/estoque/users-reserva.get').default>>>>
    }
    '/api/producao/relatorios/retiradas-semana': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/relatorios/retiradas-semana.get').default>>>>
    }
    '/api/producao/salas/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/salas/delete.post').default>>>>
    }
    '/api/producao/salas/get': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/salas/get.get').default>>>>
    }
    '/api/producao/salas/upsert': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/producao/salas/upsert.post').default>>>>
    }
    '/api/refresh-hash': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/refresh-hash').default>>>>
    }
    '/api/selecao/candidatos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/selecao/candidatos.get').default>>>>
    }
    '/api/selecao/delete-file': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/selecao/delete-file.post').default>>>>
    }
    '/api/selecao/ficha-avaliacao-config': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/selecao/ficha-avaliacao-config.post').default>>>>
    }
    '/api/selecao/fichas-avaliacao': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/selecao/fichas-avaliacao.get').default>>>>
    }
    '/api/selecao/lista-homologados': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/selecao/lista-homologados.get').default>>>>
    }
    '/api/selecao/lista-selecionados': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/selecao/lista-selecionados.get').default>>>>
    }
    '/api/selecao/parametros-homologacao': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/selecao/parametros-homologacao.post').default>>>>
    }
    '/api/selecao/status-processo': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/selecao/status-processo.post').default>>>>
    }
    '/api/selecao/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/selecao/upload.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}