// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26/01/2026, 09:06:59
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/eikmeier/Documentos/dev/nuxt/sped/front_end/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/eikmeier/Documentos/dev/nuxt/sped/front_end/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/eikmeier/Documentos/dev/nuxt/sped/front_end/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/eikmeier/Documentos/dev/nuxt/sped/front_end/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/eikmeier/Documentos/dev/nuxt/sped/front_end/app/plugins/**/*.{js,ts,mjs}","/home/eikmeier/Documentos/dev/nuxt/sped/front_end/app/composables/**/*.{js,ts,mjs}","/home/eikmeier/Documentos/dev/nuxt/sped/front_end/app/utils/**/*.{js,ts,mjs}","/home/eikmeier/Documentos/dev/nuxt/sped/front_end/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/eikmeier/Documentos/dev/nuxt/sped/front_end/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/eikmeier/Documentos/dev/nuxt/sped/front_end/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/eikmeier/Documentos/dev/nuxt/sped/front_end/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;